name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */11 * * 0-5"
   # - cron: "0 0 * * *"
   # - cron: "*/5 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: auto-commit
        run: |
          git config --local user.email "461175874@qq.com"
          git config --local user.name "whczs"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "A growing day!"
          git push
